/*
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */
package projecttone;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.MidiChannel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jobinrjohnson
 */
public class InputTone extends javax.swing.JFrame {

    AudioManager am;
    ArrayList<Instant> instants;
    HashMap<String, Instant> waiting_for_duration;
    InstantCounter counter = null;

    class InstantCounter extends Thread {

        public long timer = 0;
        public boolean terminated = false;

        public void stopTimer() {
            terminated = true;
        }

        public void resetTimer() {
            timer = 0;
        }

        public long getInstant() {
            return timer;
        }

        @Override
        public void run() {
            super.run();
            while (!terminated) {
                try {
                    sleep(1);
                    timer++;
                } catch (InterruptedException ex) {
                    Logger.getLogger(InputTone.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }

    }

    /**
     * Creates new form InputTone
     */
    public String keyToTone(int key) {
        return (StandardSet.Notes[keyToNumber(key)]);
    }

    public int keyToNumber(int key) {
        int Tone = 0;
        switch (key) {
            case 81:
                Tone = 0;
                break;
            case 87:
                Tone = 1;
                break;
            case 69:
                Tone = 2;
                break;
            case 82:
                Tone = 3;
                break;
            case 84:
                Tone = 4;
                break;
            case 89:
                Tone = 5;
                break;
            case 85:
                Tone = 6;
                break;
            case 73:
                Tone = 7;
                break;
            case 79:
                Tone = 8;
                break;
            case 80:
                Tone = 9;
                break;
            case 91:
                Tone = 10;
                break;
            case 93:
                Tone = 11;
                break;

        }
        return (Tone);
    }

    public int octave = 5;
    public InputTone() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jTextField1.setFocusable(true);

        am = new AudioManager();
        final MidiChannel[] midiChannels = AudioManager.midiChannels;

        instants = new ArrayList<Instant>();
        waiting_for_duration = new HashMap<String, Instant>();

        AudioManager.Instruments instrument = AudioManager.Instruments.PIANO;
        int mInstrument = 0;
        int strength = 90;

        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                int key = e.getKeyCode();
                if(key==38){
                    octal++;
                }
                else if(key==40){
                    octal--;
                }
                else{
                if (counter == null) {
                    counter = new InstantCounter();
                    counter.start();
                }
                Instant i = new Instant();
                i.instrument = instrument;
                i.instant = counter.getInstant();
                i.octave = 5;
                i.velocity = strength;
                i.duration_ms = 2;
                i.note = keyToTone(key);
                instants.add(i);
                waiting_for_duration.put(i.note, i);

                jTextField1.setText("");
                jLabel1.setText("Key : " + keyToTone(key));
                midiChannels[mInstrument].noteOn(StandardSet.getToneNumber(i.note, i.octave), strength);
                }
                }

            public void keyReleased(KeyEvent e) {
                int key = e.getKeyCode();
                String note = keyToTone(key);
                Instant i = waiting_for_duration.get(note);
                if (i == null) {
                    return;
                }
                i.duration_ms = (int) (counter.timer - i.instant);
                midiChannels[mInstrument].noteOff(StandardSet.getToneNumber(i.note, i.octave));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No key pressed");

        jButton1.setText("Save");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Discard");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("TONE_FOCUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Instant[] castedInstants = instants.toArray(new Instant[0]);
        counter.stopTimer();
        counter = null;
        String name = JOptionPane.showInputDialog("Save as");
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Empty String");
            return;
        }
        new Tone().saveTone(castedInstants, name.trim());
        instants.clear();
        waiting_for_duration.clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        instants.clear();
        waiting_for_duration.clear();
        counter = null;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputTone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
